import 'obd_command.dart';

class CommandDB {
  static final Map<String, OBDCommand> byName = {
    'PIDS_A': OBDCommand(
      name: 'PIDS_A',
      description: "Supported PIDs [01-20]",
      command: '0100',
      expectedBytes: 6,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'STATUS': OBDCommand(
      name: 'STATUS',
      description: "Status since DTCs cleared",
      command: '0101',
      expectedBytes: 6,
      decoderName: 'status',
      isAtCommand: false,
    ),
    'FREEZE_DTC': OBDCommand(
      name: 'FREEZE_DTC',
      description: "DTC that triggered the freeze frame",
      command: '0102',
      expectedBytes: 4,
      decoderName: 'single_dtc',
      isAtCommand: false,
    ),
    'FUEL_STATUS': OBDCommand(
      name: 'FUEL_STATUS',
      description: "Fuel System Status",
      command: '0103',
      expectedBytes: 4,
      decoderName: 'fuel_status',
      isAtCommand: false,
    ),
    'ENGINE_LOAD': OBDCommand(
      name: 'ENGINE_LOAD',
      description: "Calculated Engine Load",
      command: '0104',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'COOLANT_TEMP': OBDCommand(
      name: 'COOLANT_TEMP',
      description: "Engine Coolant Temperature",
      command: '0105',
      expectedBytes: 3,
      decoderName: 'temp',
      isAtCommand: false,
    ),
    'SHORT_FUEL_TRIM_1': OBDCommand(
      name: 'SHORT_FUEL_TRIM_1',
      description: "Short Term Fuel Trim - Bank 1",
      command: '0106',
      expectedBytes: 3,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'LONG_FUEL_TRIM_1': OBDCommand(
      name: 'LONG_FUEL_TRIM_1',
      description: "Long Term Fuel Trim - Bank 1",
      command: '0107',
      expectedBytes: 3,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'SHORT_FUEL_TRIM_2': OBDCommand(
      name: 'SHORT_FUEL_TRIM_2',
      description: "Short Term Fuel Trim - Bank 2",
      command: '0108',
      expectedBytes: 3,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'LONG_FUEL_TRIM_2': OBDCommand(
      name: 'LONG_FUEL_TRIM_2',
      description: "Long Term Fuel Trim - Bank 2",
      command: '0109',
      expectedBytes: 3,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'FUEL_PRESSURE': OBDCommand(
      name: 'FUEL_PRESSURE',
      description: "Fuel Pressure",
      command: '010A',
      expectedBytes: 3,
      decoderName: 'fuel_pressure',
      isAtCommand: false,
    ),
    'INTAKE_PRESSURE': OBDCommand(
      name: 'INTAKE_PRESSURE',
      description: "Intake Manifold Pressure",
      command: '010B',
      expectedBytes: 3,
      decoderName: 'pressure',
      isAtCommand: false,
    ),
    'RPM': OBDCommand(
      name: 'RPM',
      description: "Engine RPM",
      command: '010C',
      expectedBytes: 4,
      decoderName: 'uas(0x07)',
      isAtCommand: false,
    ),
    'SPEED': OBDCommand(
      name: 'SPEED',
      description: "Vehicle Speed",
      command: '010D',
      expectedBytes: 3,
      decoderName: 'uas(0x09)',
      isAtCommand: false,
    ),
    'TIMING_ADVANCE': OBDCommand(
      name: 'TIMING_ADVANCE',
      description: "Timing Advance",
      command: '010E',
      expectedBytes: 3,
      decoderName: 'timing_advance',
      isAtCommand: false,
    ),
    'INTAKE_TEMP': OBDCommand(
      name: 'INTAKE_TEMP',
      description: "Intake Air Temp",
      command: '010F',
      expectedBytes: 3,
      decoderName: 'temp',
      isAtCommand: false,
    ),
    'MAF': OBDCommand(
      name: 'MAF',
      description: "Air Flow Rate (MAF)",
      command: '0110',
      expectedBytes: 4,
      decoderName: 'uas(0x27)',
      isAtCommand: false,
    ),
    'THROTTLE_POS': OBDCommand(
      name: 'THROTTLE_POS',
      description: "Throttle Position",
      command: '0111',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'AIR_STATUS': OBDCommand(
      name: 'AIR_STATUS',
      description: "Secondary Air Status",
      command: '0112',
      expectedBytes: 3,
      decoderName: 'air_status',
      isAtCommand: false,
    ),
    'O2_SENSORS': OBDCommand(
      name: 'O2_SENSORS',
      description: "O2 Sensors Present",
      command: '0113',
      expectedBytes: 3,
      decoderName: 'o2_sensors',
      isAtCommand: false,
    ),
    'O2_B1S1': OBDCommand(
      name: 'O2_B1S1',
      description: "O2: Bank 1 - Sensor 1 Voltage",
      command: '0114',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'O2_B1S2': OBDCommand(
      name: 'O2_B1S2',
      description: "O2: Bank 1 - Sensor 2 Voltage",
      command: '0115',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'O2_B1S3': OBDCommand(
      name: 'O2_B1S3',
      description: "O2: Bank 1 - Sensor 3 Voltage",
      command: '0116',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'O2_B1S4': OBDCommand(
      name: 'O2_B1S4',
      description: "O2: Bank 1 - Sensor 4 Voltage",
      command: '0117',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'O2_B2S1': OBDCommand(
      name: 'O2_B2S1',
      description: "O2: Bank 2 - Sensor 1 Voltage",
      command: '0118',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'O2_B2S2': OBDCommand(
      name: 'O2_B2S2',
      description: "O2: Bank 2 - Sensor 2 Voltage",
      command: '0119',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'O2_B2S3': OBDCommand(
      name: 'O2_B2S3',
      description: "O2: Bank 2 - Sensor 3 Voltage",
      command: '011A',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'O2_B2S4': OBDCommand(
      name: 'O2_B2S4',
      description: "O2: Bank 2 - Sensor 4 Voltage",
      command: '011B',
      expectedBytes: 4,
      decoderName: 'sensor_voltage',
      isAtCommand: false,
    ),
    'OBD_COMPLIANCE': OBDCommand(
      name: 'OBD_COMPLIANCE',
      description: "OBD Standards Compliance",
      command: '011C',
      expectedBytes: 3,
      decoderName: 'obd_compliance',
      isAtCommand: false,
    ),
    'O2_SENSORS_ALT': OBDCommand(
      name: 'O2_SENSORS_ALT',
      description: "O2 Sensors Present (alternate)",
      command: '011D',
      expectedBytes: 3,
      decoderName: 'o2_sensors_alt',
      isAtCommand: false,
    ),
    'AUX_INPUT_STATUS': OBDCommand(
      name: 'AUX_INPUT_STATUS',
      description: "Auxiliary input status (power take off)",
      command: '011E',
      expectedBytes: 3,
      decoderName: 'aux_input_status',
      isAtCommand: false,
    ),
    'RUN_TIME': OBDCommand(
      name: 'RUN_TIME',
      description: "Engine Run Time",
      command: '011F',
      expectedBytes: 4,
      decoderName: 'uas(0x12)',
      isAtCommand: false,
    ),
    'PIDS_B': OBDCommand(
      name: 'PIDS_B',
      description: "Supported PIDs [21-40]",
      command: '0120',
      expectedBytes: 6,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'DISTANCE_W_MIL': OBDCommand(
      name: 'DISTANCE_W_MIL',
      description: "Distance Traveled with MIL on",
      command: '0121',
      expectedBytes: 4,
      decoderName: 'uas(0x25)',
      isAtCommand: false,
    ),
    'FUEL_RAIL_PRESSURE_VAC': OBDCommand(
      name: 'FUEL_RAIL_PRESSURE_VAC',
      description: "Fuel Rail Pressure (relative to vacuum)",
      command: '0122',
      expectedBytes: 4,
      decoderName: 'uas(0x19)',
      isAtCommand: false,
    ),
    'FUEL_RAIL_PRESSURE_DIRECT': OBDCommand(
      name: 'FUEL_RAIL_PRESSURE_DIRECT',
      description: "Fuel Rail Pressure (direct inject)",
      command: '0123',
      expectedBytes: 4,
      decoderName: 'uas(0x1B)',
      isAtCommand: false,
    ),
    'O2_S1_WR_VOLTAGE': OBDCommand(
      name: 'O2_S1_WR_VOLTAGE',
      description: "02 Sensor 1 WR Lambda Voltage",
      command: '0124',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'O2_S2_WR_VOLTAGE': OBDCommand(
      name: 'O2_S2_WR_VOLTAGE',
      description: "02 Sensor 2 WR Lambda Voltage",
      command: '0125',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'O2_S3_WR_VOLTAGE': OBDCommand(
      name: 'O2_S3_WR_VOLTAGE',
      description: "02 Sensor 3 WR Lambda Voltage",
      command: '0126',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'O2_S4_WR_VOLTAGE': OBDCommand(
      name: 'O2_S4_WR_VOLTAGE',
      description: "02 Sensor 4 WR Lambda Voltage",
      command: '0127',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'O2_S5_WR_VOLTAGE': OBDCommand(
      name: 'O2_S5_WR_VOLTAGE',
      description: "02 Sensor 5 WR Lambda Voltage",
      command: '0128',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'O2_S6_WR_VOLTAGE': OBDCommand(
      name: 'O2_S6_WR_VOLTAGE',
      description: "02 Sensor 6 WR Lambda Voltage",
      command: '0129',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'O2_S7_WR_VOLTAGE': OBDCommand(
      name: 'O2_S7_WR_VOLTAGE',
      description: "02 Sensor 7 WR Lambda Voltage",
      command: '012A',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'O2_S8_WR_VOLTAGE': OBDCommand(
      name: 'O2_S8_WR_VOLTAGE',
      description: "02 Sensor 8 WR Lambda Voltage",
      command: '012B',
      expectedBytes: 6,
      decoderName: 'sensor_voltage_big',
      isAtCommand: false,
    ),
    'COMMANDED_EGR': OBDCommand(
      name: 'COMMANDED_EGR',
      description: "Commanded EGR",
      command: '012C',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'EGR_ERROR': OBDCommand(
      name: 'EGR_ERROR',
      description: "EGR Error",
      command: '012D',
      expectedBytes: 3,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'EVAPORATIVE_PURGE': OBDCommand(
      name: 'EVAPORATIVE_PURGE',
      description: "Commanded Evaporative Purge",
      command: '012E',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'FUEL_LEVEL': OBDCommand(
      name: 'FUEL_LEVEL',
      description: "Fuel Level Input",
      command: '012F',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'WARMUPS_SINCE_DTC_CLEAR': OBDCommand(
      name: 'WARMUPS_SINCE_DTC_CLEAR',
      description: "Number of warm-ups since codes cleared",
      command: '0130',
      expectedBytes: 3,
      decoderName: 'uas(0x01)',
      isAtCommand: false,
    ),
    'DISTANCE_SINCE_DTC_CLEAR': OBDCommand(
      name: 'DISTANCE_SINCE_DTC_CLEAR',
      description: "Distance traveled since codes cleared",
      command: '0131',
      expectedBytes: 4,
      decoderName: 'uas(0x25)',
      isAtCommand: false,
    ),
    'EVAP_VAPOR_PRESSURE': OBDCommand(
      name: 'EVAP_VAPOR_PRESSURE',
      description: "Evaporative system vapor pressure",
      command: '0132',
      expectedBytes: 4,
      decoderName: 'evap_pressure',
      isAtCommand: false,
    ),
    'BAROMETRIC_PRESSURE': OBDCommand(
      name: 'BAROMETRIC_PRESSURE',
      description: "Barometric Pressure",
      command: '0133',
      expectedBytes: 3,
      decoderName: 'pressure',
      isAtCommand: false,
    ),
    'O2_S1_WR_CURRENT': OBDCommand(
      name: 'O2_S1_WR_CURRENT',
      description: "02 Sensor 1 WR Lambda Current",
      command: '0134',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'O2_S2_WR_CURRENT': OBDCommand(
      name: 'O2_S2_WR_CURRENT',
      description: "02 Sensor 2 WR Lambda Current",
      command: '0135',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'O2_S3_WR_CURRENT': OBDCommand(
      name: 'O2_S3_WR_CURRENT',
      description: "02 Sensor 3 WR Lambda Current",
      command: '0136',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'O2_S4_WR_CURRENT': OBDCommand(
      name: 'O2_S4_WR_CURRENT',
      description: "02 Sensor 4 WR Lambda Current",
      command: '0137',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'O2_S5_WR_CURRENT': OBDCommand(
      name: 'O2_S5_WR_CURRENT',
      description: "02 Sensor 5 WR Lambda Current",
      command: '0138',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'O2_S6_WR_CURRENT': OBDCommand(
      name: 'O2_S6_WR_CURRENT',
      description: "02 Sensor 6 WR Lambda Current",
      command: '0139',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'O2_S7_WR_CURRENT': OBDCommand(
      name: 'O2_S7_WR_CURRENT',
      description: "02 Sensor 7 WR Lambda Current",
      command: '013A',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'O2_S8_WR_CURRENT': OBDCommand(
      name: 'O2_S8_WR_CURRENT',
      description: "02 Sensor 8 WR Lambda Current",
      command: '013B',
      expectedBytes: 6,
      decoderName: 'current_centered',
      isAtCommand: false,
    ),
    'CATALYST_TEMP_B1S1': OBDCommand(
      name: 'CATALYST_TEMP_B1S1',
      description: "Catalyst Temperature: Bank 1 - Sensor 1",
      command: '013C',
      expectedBytes: 4,
      decoderName: 'uas(0x16)',
      isAtCommand: false,
    ),
    'CATALYST_TEMP_B2S1': OBDCommand(
      name: 'CATALYST_TEMP_B2S1',
      description: "Catalyst Temperature: Bank 2 - Sensor 1",
      command: '013D',
      expectedBytes: 4,
      decoderName: 'uas(0x16)',
      isAtCommand: false,
    ),
    'CATALYST_TEMP_B1S2': OBDCommand(
      name: 'CATALYST_TEMP_B1S2',
      description: "Catalyst Temperature: Bank 1 - Sensor 2",
      command: '013E',
      expectedBytes: 4,
      decoderName: 'uas(0x16)',
      isAtCommand: false,
    ),
    'CATALYST_TEMP_B2S2': OBDCommand(
      name: 'CATALYST_TEMP_B2S2',
      description: "Catalyst Temperature: Bank 2 - Sensor 2",
      command: '013F',
      expectedBytes: 4,
      decoderName: 'uas(0x16)',
      isAtCommand: false,
    ),
    'PIDS_C': OBDCommand(
      name: 'PIDS_C',
      description: "Supported PIDs [41-60]",
      command: '0140',
      expectedBytes: 6,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'STATUS_DRIVE_CYCLE': OBDCommand(
      name: 'STATUS_DRIVE_CYCLE',
      description: "Monitor status this drive cycle",
      command: '0141',
      expectedBytes: 6,
      decoderName: 'status',
      isAtCommand: false,
    ),
    'CONTROL_MODULE_VOLTAGE': OBDCommand(
      name: 'CONTROL_MODULE_VOLTAGE',
      description: "Control module voltage",
      command: '0142',
      expectedBytes: 4,
      decoderName: 'uas(0x0B)',
      isAtCommand: false,
    ),
    'ABSOLUTE_LOAD': OBDCommand(
      name: 'ABSOLUTE_LOAD',
      description: "Absolute load value",
      command: '0143',
      expectedBytes: 4,
      decoderName: 'absolute_load',
      isAtCommand: false,
    ),
    'COMMANDED_EQUIV_RATIO': OBDCommand(
      name: 'COMMANDED_EQUIV_RATIO',
      description: "Commanded equivalence ratio",
      command: '0144',
      expectedBytes: 4,
      decoderName: 'uas(0x1E)',
      isAtCommand: false,
    ),
    'RELATIVE_THROTTLE_POS': OBDCommand(
      name: 'RELATIVE_THROTTLE_POS',
      description: "Relative throttle position",
      command: '0145',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'AMBIANT_AIR_TEMP': OBDCommand(
      name: 'AMBIANT_AIR_TEMP',
      description: "Ambient air temperature",
      command: '0146',
      expectedBytes: 3,
      decoderName: 'temp',
      isAtCommand: false,
    ),
    'THROTTLE_POS_B': OBDCommand(
      name: 'THROTTLE_POS_B',
      description: "Absolute throttle position B",
      command: '0147',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'THROTTLE_POS_C': OBDCommand(
      name: 'THROTTLE_POS_C',
      description: "Absolute throttle position C",
      command: '0148',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'ACCELERATOR_POS_D': OBDCommand(
      name: 'ACCELERATOR_POS_D',
      description: "Accelerator pedal position D",
      command: '0149',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'ACCELERATOR_POS_E': OBDCommand(
      name: 'ACCELERATOR_POS_E',
      description: "Accelerator pedal position E",
      command: '014A',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'ACCELERATOR_POS_F': OBDCommand(
      name: 'ACCELERATOR_POS_F',
      description: "Accelerator pedal position F",
      command: '014B',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'THROTTLE_ACTUATOR': OBDCommand(
      name: 'THROTTLE_ACTUATOR',
      description: "Commanded throttle actuator",
      command: '014C',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'RUN_TIME_MIL': OBDCommand(
      name: 'RUN_TIME_MIL',
      description: "Time run with MIL on",
      command: '014D',
      expectedBytes: 4,
      decoderName: 'uas(0x34)',
      isAtCommand: false,
    ),
    'TIME_SINCE_DTC_CLEARED': OBDCommand(
      name: 'TIME_SINCE_DTC_CLEARED',
      description: "Time since trouble codes cleared",
      command: '014E',
      expectedBytes: 4,
      decoderName: 'uas(0x34)',
      isAtCommand: false,
    ),
    'MAX_VALUES': OBDCommand(
      name: 'MAX_VALUES',
      description: "Various Max values",
      command: '014F',
      expectedBytes: 6,
      decoderName: 'drop',
      isAtCommand: false,
    ),
    'MAX_MAF': OBDCommand(
      name: 'MAX_MAF',
      description: "Maximum value for mass air flow sensor",
      command: '0150',
      expectedBytes: 6,
      decoderName: 'max_maf',
      isAtCommand: false,
    ),
    'FUEL_TYPE': OBDCommand(
      name: 'FUEL_TYPE',
      description: "Fuel Type",
      command: '0151',
      expectedBytes: 3,
      decoderName: 'fuel_type',
      isAtCommand: false,
    ),
    'ETHANOL_PERCENT': OBDCommand(
      name: 'ETHANOL_PERCENT',
      description: "Ethanol Fuel Percent",
      command: '0152',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'EVAP_VAPOR_PRESSURE_ABS': OBDCommand(
      name: 'EVAP_VAPOR_PRESSURE_ABS',
      description: "Absolute Evap system Vapor Pressure",
      command: '0153',
      expectedBytes: 4,
      decoderName: 'abs_evap_pressure',
      isAtCommand: false,
    ),
    'EVAP_VAPOR_PRESSURE_ALT': OBDCommand(
      name: 'EVAP_VAPOR_PRESSURE_ALT',
      description: "Evap system vapor pressure",
      command: '0154',
      expectedBytes: 4,
      decoderName: 'evap_pressure_alt',
      isAtCommand: false,
    ),
    'SHORT_O2_TRIM_B1': OBDCommand(
      name: 'SHORT_O2_TRIM_B1',
      description: "Short term secondary O2 trim - Bank 1",
      command: '0155',
      expectedBytes: 4,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'LONG_O2_TRIM_B1': OBDCommand(
      name: 'LONG_O2_TRIM_B1',
      description: "Long term secondary O2 trim - Bank 1",
      command: '0156',
      expectedBytes: 4,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'SHORT_O2_TRIM_B2': OBDCommand(
      name: 'SHORT_O2_TRIM_B2',
      description: "Short term secondary O2 trim - Bank 2",
      command: '0157',
      expectedBytes: 4,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'LONG_O2_TRIM_B2': OBDCommand(
      name: 'LONG_O2_TRIM_B2',
      description: "Long term secondary O2 trim - Bank 2",
      command: '0158',
      expectedBytes: 4,
      decoderName: 'percent_centered',
      isAtCommand: false,
    ),
    'FUEL_RAIL_PRESSURE_ABS': OBDCommand(
      name: 'FUEL_RAIL_PRESSURE_ABS',
      description: "Fuel rail pressure (absolute)",
      command: '0159',
      expectedBytes: 4,
      decoderName: 'uas(0x1B)',
      isAtCommand: false,
    ),
    'RELATIVE_ACCEL_POS': OBDCommand(
      name: 'RELATIVE_ACCEL_POS',
      description: "Relative accelerator pedal position",
      command: '015A',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'HYBRID_BATTERY_REMAINING': OBDCommand(
      name: 'HYBRID_BATTERY_REMAINING',
      description: "Hybrid battery pack remaining life",
      command: '015B',
      expectedBytes: 3,
      decoderName: 'percent',
      isAtCommand: false,
    ),
    'OIL_TEMP': OBDCommand(
      name: 'OIL_TEMP',
      description: "Engine oil temperature",
      command: '015C',
      expectedBytes: 3,
      decoderName: 'temp',
      isAtCommand: false,
    ),
    'FUEL_INJECT_TIMING': OBDCommand(
      name: 'FUEL_INJECT_TIMING',
      description: "Fuel injection timing",
      command: '015D',
      expectedBytes: 4,
      decoderName: 'inject_timing',
      isAtCommand: false,
    ),
    'FUEL_RATE': OBDCommand(
      name: 'FUEL_RATE',
      description: "Engine fuel rate",
      command: '015E',
      expectedBytes: 4,
      decoderName: 'fuel_rate',
      isAtCommand: false,
    ),
    'EMISSION_REQ': OBDCommand(
      name: 'EMISSION_REQ',
      description: "Designed emission requirements",
      command: '015F',
      expectedBytes: 3,
      decoderName: 'drop',
      isAtCommand: false,
    ),
    'GET_DTC': OBDCommand(
      name: 'GET_DTC',
      description: "Get DTCs",
      command: '03',
      expectedBytes: 0,
      decoderName: 'dtc',
      isAtCommand: false,
    ),
    'CLEAR_DTC': OBDCommand(
      name: 'CLEAR_DTC',
      description: "Clear DTCs and Freeze data",
      command: '04',
      expectedBytes: 0,
      decoderName: 'drop',
      isAtCommand: false,
    ),
    'MIDS_A': OBDCommand(
      name: 'MIDS_A',
      description: "Supported MIDs [01-20]",
      command: '0600',
      expectedBytes: 0,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'MONITOR_O2_B1S1': OBDCommand(
      name: 'MONITOR_O2_B1S1',
      description: "O2 Sensor Monitor Bank 1 - Sensor 1",
      command: '0601',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B1S2': OBDCommand(
      name: 'MONITOR_O2_B1S2',
      description: "O2 Sensor Monitor Bank 1 - Sensor 2",
      command: '0602',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B1S3': OBDCommand(
      name: 'MONITOR_O2_B1S3',
      description: "O2 Sensor Monitor Bank 1 - Sensor 3",
      command: '0603',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B1S4': OBDCommand(
      name: 'MONITOR_O2_B1S4',
      description: "O2 Sensor Monitor Bank 1 - Sensor 4",
      command: '0604',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B2S1': OBDCommand(
      name: 'MONITOR_O2_B2S1',
      description: "O2 Sensor Monitor Bank 2 - Sensor 1",
      command: '0605',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B2S2': OBDCommand(
      name: 'MONITOR_O2_B2S2',
      description: "O2 Sensor Monitor Bank 2 - Sensor 2",
      command: '0606',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B2S3': OBDCommand(
      name: 'MONITOR_O2_B2S3',
      description: "O2 Sensor Monitor Bank 2 - Sensor 3",
      command: '0607',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B2S4': OBDCommand(
      name: 'MONITOR_O2_B2S4',
      description: "O2 Sensor Monitor Bank 2 - Sensor 4",
      command: '0608',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B3S1': OBDCommand(
      name: 'MONITOR_O2_B3S1',
      description: "O2 Sensor Monitor Bank 3 - Sensor 1",
      command: '0609',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B3S2': OBDCommand(
      name: 'MONITOR_O2_B3S2',
      description: "O2 Sensor Monitor Bank 3 - Sensor 2",
      command: '060A',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B3S3': OBDCommand(
      name: 'MONITOR_O2_B3S3',
      description: "O2 Sensor Monitor Bank 3 - Sensor 3",
      command: '060B',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B3S4': OBDCommand(
      name: 'MONITOR_O2_B3S4',
      description: "O2 Sensor Monitor Bank 3 - Sensor 4",
      command: '060C',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B4S1': OBDCommand(
      name: 'MONITOR_O2_B4S1',
      description: "O2 Sensor Monitor Bank 4 - Sensor 1",
      command: '060D',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B4S2': OBDCommand(
      name: 'MONITOR_O2_B4S2',
      description: "O2 Sensor Monitor Bank 4 - Sensor 2",
      command: '060E',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B4S3': OBDCommand(
      name: 'MONITOR_O2_B4S3',
      description: "O2 Sensor Monitor Bank 4 - Sensor 3",
      command: '060F',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_B4S4': OBDCommand(
      name: 'MONITOR_O2_B4S4',
      description: "O2 Sensor Monitor Bank 4 - Sensor 4",
      command: '0610',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MIDS_B': OBDCommand(
      name: 'MIDS_B',
      description: "Supported MIDs [21-40]",
      command: '0620',
      expectedBytes: 0,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'MONITOR_CATALYST_B1': OBDCommand(
      name: 'MONITOR_CATALYST_B1',
      description: "Catalyst Monitor Bank 1",
      command: '0621',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_CATALYST_B2': OBDCommand(
      name: 'MONITOR_CATALYST_B2',
      description: "Catalyst Monitor Bank 2",
      command: '0622',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_CATALYST_B3': OBDCommand(
      name: 'MONITOR_CATALYST_B3',
      description: "Catalyst Monitor Bank 3",
      command: '0623',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_CATALYST_B4': OBDCommand(
      name: 'MONITOR_CATALYST_B4',
      description: "Catalyst Monitor Bank 4",
      command: '0624',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EGR_B1': OBDCommand(
      name: 'MONITOR_EGR_B1',
      description: "EGR Monitor Bank 1",
      command: '0631',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EGR_B2': OBDCommand(
      name: 'MONITOR_EGR_B2',
      description: "EGR Monitor Bank 2",
      command: '0632',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EGR_B3': OBDCommand(
      name: 'MONITOR_EGR_B3',
      description: "EGR Monitor Bank 3",
      command: '0633',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EGR_B4': OBDCommand(
      name: 'MONITOR_EGR_B4',
      description: "EGR Monitor Bank 4",
      command: '0634',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_VVT_B1': OBDCommand(
      name: 'MONITOR_VVT_B1',
      description: "VVT Monitor Bank 1",
      command: '0635',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_VVT_B2': OBDCommand(
      name: 'MONITOR_VVT_B2',
      description: "VVT Monitor Bank 2",
      command: '0636',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_VVT_B3': OBDCommand(
      name: 'MONITOR_VVT_B3',
      description: "VVT Monitor Bank 3",
      command: '0637',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_VVT_B4': OBDCommand(
      name: 'MONITOR_VVT_B4',
      description: "VVT Monitor Bank 4",
      command: '0638',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EVAP_150': OBDCommand(
      name: 'MONITOR_EVAP_150',
      description: "EVAP Monitor (Cap Off / 0.150\")",
      command: '0639',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EVAP_090': OBDCommand(
      name: 'MONITOR_EVAP_090',
      description: "EVAP Monitor (0.090\")",
      command: '063A',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EVAP_040': OBDCommand(
      name: 'MONITOR_EVAP_040',
      description: "EVAP Monitor (0.040\")",
      command: '063B',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_EVAP_020': OBDCommand(
      name: 'MONITOR_EVAP_020',
      description: "EVAP Monitor (0.020\")",
      command: '063C',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_PURGE_FLOW': OBDCommand(
      name: 'MONITOR_PURGE_FLOW',
      description: "Purge Flow Monitor",
      command: '063D',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MIDS_C': OBDCommand(
      name: 'MIDS_C',
      description: "Supported MIDs [41-60]",
      command: '0640',
      expectedBytes: 0,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B1S1': OBDCommand(
      name: 'MONITOR_O2_HEATER_B1S1',
      description: "O2 Sensor Heater Monitor Bank 1 - Sensor 1",
      command: '0641',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B1S2': OBDCommand(
      name: 'MONITOR_O2_HEATER_B1S2',
      description: "O2 Sensor Heater Monitor Bank 1 - Sensor 2",
      command: '0642',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B1S3': OBDCommand(
      name: 'MONITOR_O2_HEATER_B1S3',
      description: "O2 Sensor Heater Monitor Bank 1 - Sensor 3",
      command: '0643',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B1S4': OBDCommand(
      name: 'MONITOR_O2_HEATER_B1S4',
      description: "O2 Sensor Heater Monitor Bank 1 - Sensor 4",
      command: '0644',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B2S1': OBDCommand(
      name: 'MONITOR_O2_HEATER_B2S1',
      description: "O2 Sensor Heater Monitor Bank 2 - Sensor 1",
      command: '0645',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B2S2': OBDCommand(
      name: 'MONITOR_O2_HEATER_B2S2',
      description: "O2 Sensor Heater Monitor Bank 2 - Sensor 2",
      command: '0646',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B2S3': OBDCommand(
      name: 'MONITOR_O2_HEATER_B2S3',
      description: "O2 Sensor Heater Monitor Bank 2 - Sensor 3",
      command: '0647',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B2S4': OBDCommand(
      name: 'MONITOR_O2_HEATER_B2S4',
      description: "O2 Sensor Heater Monitor Bank 2 - Sensor 4",
      command: '0648',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B3S1': OBDCommand(
      name: 'MONITOR_O2_HEATER_B3S1',
      description: "O2 Sensor Heater Monitor Bank 3 - Sensor 1",
      command: '0649',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B3S2': OBDCommand(
      name: 'MONITOR_O2_HEATER_B3S2',
      description: "O2 Sensor Heater Monitor Bank 3 - Sensor 2",
      command: '064A',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B3S3': OBDCommand(
      name: 'MONITOR_O2_HEATER_B3S3',
      description: "O2 Sensor Heater Monitor Bank 3 - Sensor 3",
      command: '064B',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B3S4': OBDCommand(
      name: 'MONITOR_O2_HEATER_B3S4',
      description: "O2 Sensor Heater Monitor Bank 3 - Sensor 4",
      command: '064C',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B4S1': OBDCommand(
      name: 'MONITOR_O2_HEATER_B4S1',
      description: "O2 Sensor Heater Monitor Bank 4 - Sensor 1",
      command: '064D',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B4S2': OBDCommand(
      name: 'MONITOR_O2_HEATER_B4S2',
      description: "O2 Sensor Heater Monitor Bank 4 - Sensor 2",
      command: '064E',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B4S3': OBDCommand(
      name: 'MONITOR_O2_HEATER_B4S3',
      description: "O2 Sensor Heater Monitor Bank 4 - Sensor 3",
      command: '064F',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_O2_HEATER_B4S4': OBDCommand(
      name: 'MONITOR_O2_HEATER_B4S4',
      description: "O2 Sensor Heater Monitor Bank 4 - Sensor 4",
      command: '0650',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MIDS_D': OBDCommand(
      name: 'MIDS_D',
      description: "Supported MIDs [61-80]",
      command: '0660',
      expectedBytes: 0,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'MONITOR_HEATED_CATALYST_B1': OBDCommand(
      name: 'MONITOR_HEATED_CATALYST_B1',
      description: "Heated Catalyst Monitor Bank 1",
      command: '0661',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_HEATED_CATALYST_B2': OBDCommand(
      name: 'MONITOR_HEATED_CATALYST_B2',
      description: "Heated Catalyst Monitor Bank 2",
      command: '0662',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_HEATED_CATALYST_B3': OBDCommand(
      name: 'MONITOR_HEATED_CATALYST_B3',
      description: "Heated Catalyst Monitor Bank 3",
      command: '0663',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_HEATED_CATALYST_B4': OBDCommand(
      name: 'MONITOR_HEATED_CATALYST_B4',
      description: "Heated Catalyst Monitor Bank 4",
      command: '0664',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_SECONDARY_AIR_1': OBDCommand(
      name: 'MONITOR_SECONDARY_AIR_1',
      description: "Secondary Air Monitor 1",
      command: '0671',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_SECONDARY_AIR_2': OBDCommand(
      name: 'MONITOR_SECONDARY_AIR_2',
      description: "Secondary Air Monitor 2",
      command: '0672',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_SECONDARY_AIR_3': OBDCommand(
      name: 'MONITOR_SECONDARY_AIR_3',
      description: "Secondary Air Monitor 3",
      command: '0673',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_SECONDARY_AIR_4': OBDCommand(
      name: 'MONITOR_SECONDARY_AIR_4',
      description: "Secondary Air Monitor 4",
      command: '0674',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MIDS_E': OBDCommand(
      name: 'MIDS_E',
      description: "Supported MIDs [81-A0]",
      command: '0680',
      expectedBytes: 0,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'MONITOR_FUEL_SYSTEM_B1': OBDCommand(
      name: 'MONITOR_FUEL_SYSTEM_B1',
      description: "Fuel System Monitor Bank 1",
      command: '0681',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_FUEL_SYSTEM_B2': OBDCommand(
      name: 'MONITOR_FUEL_SYSTEM_B2',
      description: "Fuel System Monitor Bank 2",
      command: '0682',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_FUEL_SYSTEM_B3': OBDCommand(
      name: 'MONITOR_FUEL_SYSTEM_B3',
      description: "Fuel System Monitor Bank 3",
      command: '0683',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_FUEL_SYSTEM_B4': OBDCommand(
      name: 'MONITOR_FUEL_SYSTEM_B4',
      description: "Fuel System Monitor Bank 4",
      command: '0684',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_BOOST_PRESSURE_B1': OBDCommand(
      name: 'MONITOR_BOOST_PRESSURE_B1',
      description: "Boost Pressure Control Monitor Bank 1",
      command: '0685',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_BOOST_PRESSURE_B2': OBDCommand(
      name: 'MONITOR_BOOST_PRESSURE_B2',
      description: "Boost Pressure Control Monitor Bank 1",
      command: '0686',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_NOX_ABSORBER_B1': OBDCommand(
      name: 'MONITOR_NOX_ABSORBER_B1',
      description: "NOx Absorber Monitor Bank 1",
      command: '0690',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_NOX_ABSORBER_B2': OBDCommand(
      name: 'MONITOR_NOX_ABSORBER_B2',
      description: "NOx Absorber Monitor Bank 2",
      command: '0691',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_NOX_CATALYST_B1': OBDCommand(
      name: 'MONITOR_NOX_CATALYST_B1',
      description: "NOx Catalyst Monitor Bank 1",
      command: '0698',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_NOX_CATALYST_B2': OBDCommand(
      name: 'MONITOR_NOX_CATALYST_B2',
      description: "NOx Catalyst Monitor Bank 2",
      command: '0699',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MIDS_F': OBDCommand(
      name: 'MIDS_F',
      description: "Supported MIDs [A1-C0]",
      command: '06A0',
      expectedBytes: 0,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_GENERAL': OBDCommand(
      name: 'MONITOR_MISFIRE_GENERAL',
      description: "Misfire Monitor General Data",
      command: '06A1',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_1': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_1',
      description: "Misfire Cylinder 1 Data",
      command: '06A2',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_2': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_2',
      description: "Misfire Cylinder 2 Data",
      command: '06A3',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_3': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_3',
      description: "Misfire Cylinder 3 Data",
      command: '06A4',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_4': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_4',
      description: "Misfire Cylinder 4 Data",
      command: '06A5',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_5': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_5',
      description: "Misfire Cylinder 5 Data",
      command: '06A6',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_6': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_6',
      description: "Misfire Cylinder 6 Data",
      command: '06A7',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_7': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_7',
      description: "Misfire Cylinder 7 Data",
      command: '06A8',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_8': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_8',
      description: "Misfire Cylinder 8 Data",
      command: '06A9',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_9': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_9',
      description: "Misfire Cylinder 9 Data",
      command: '06AA',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_10': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_10',
      description: "Misfire Cylinder 10 Data",
      command: '06AB',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_11': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_11',
      description: "Misfire Cylinder 11 Data",
      command: '06AC',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_MISFIRE_CYLINDER_12': OBDCommand(
      name: 'MONITOR_MISFIRE_CYLINDER_12',
      description: "Misfire Cylinder 12 Data",
      command: '06AD',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_PM_FILTER_B1': OBDCommand(
      name: 'MONITOR_PM_FILTER_B1',
      description: "PM Filter Monitor Bank 1",
      command: '06B0',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'MONITOR_PM_FILTER_B2': OBDCommand(
      name: 'MONITOR_PM_FILTER_B2',
      description: "PM Filter Monitor Bank 2",
      command: '06B1',
      expectedBytes: 0,
      decoderName: 'monitor',
      isAtCommand: false,
    ),
    'GET_CURRENT_DTC': OBDCommand(
      name: 'GET_CURRENT_DTC',
      description: "Get DTCs from the current/last driving cycle",
      command: '07',
      expectedBytes: 0,
      decoderName: 'dtc',
      isAtCommand: false,
    ),
    'PIDS_9A': OBDCommand(
      name: 'PIDS_9A',
      description: "Supported PIDs [01-20]",
      command: '0900',
      expectedBytes: 7,
      decoderName: 'pid',
      isAtCommand: false,
    ),
    'VIN_MESSAGE_COUNT': OBDCommand(
      name: 'VIN_MESSAGE_COUNT',
      description: "VIN Message Count",
      command: '0901',
      expectedBytes: 3,
      decoderName: 'count',
      isAtCommand: false,
    ),
    'VIN': OBDCommand(
      name: 'VIN',
      description: "Vehicle Identification Number",
      command: '0902',
      expectedBytes: 22,
      decoderName: 'encoded_string(17)',
      isAtCommand: false,
    ),
    'CALIBRATION_ID_MESSAGE_COUNT': OBDCommand(
      name: 'CALIBRATION_ID_MESSAGE_COUNT',
      description: "Calibration ID message count for PID 04",
      command: '0903',
      expectedBytes: 3,
      decoderName: 'count',
      isAtCommand: false,
    ),
    'CALIBRATION_ID': OBDCommand(
      name: 'CALIBRATION_ID',
      description: "Calibration ID",
      command: '0904',
      expectedBytes: 18,
      decoderName: 'encoded_string(16)',
      isAtCommand: false,
    ),
    'CVN_MESSAGE_COUNT': OBDCommand(
      name: 'CVN_MESSAGE_COUNT',
      description: "CVN Message Count for PID 06",
      command: '0905',
      expectedBytes: 3,
      decoderName: 'count',
      isAtCommand: false,
    ),
    'CVN': OBDCommand(
      name: 'CVN',
      description: "Calibration Verification Numbers",
      command: '0906',
      expectedBytes: 10,
      decoderName: 'cvn',
      isAtCommand: false,
    ),
    'PERF_TRACKING_MESSAGE_COUNT': OBDCommand(
      name: 'PERF_TRACKING_MESSAGE_COUNT',
      description: "Performance tracking message count",
      command: '0907',
      expectedBytes: 3,
      decoderName: 'count',
      isAtCommand: false,
    ),
    'PERF_TRACKING_SPARK': OBDCommand(
      name: 'PERF_TRACKING_SPARK',
      description: "In-use performance tracking (spark ignition)",
      command: '0908',
      expectedBytes: 4,
      decoderName: 'raw_string',
      isAtCommand: false,
    ),
    'ECU_NAME_MESSAGE_COUNT': OBDCommand(
      name: 'ECU_NAME_MESSAGE_COUNT',
      description: "ECU Name Message Count for PID 0A",
      command: '0909',
      expectedBytes: 3,
      decoderName: 'count',
      isAtCommand: false,
    ),
    'ECU_NAME': OBDCommand(
      name: 'ECU_NAME',
      description: "ECU Name",
      command: '090A',
      expectedBytes: 20,
      decoderName: 'raw_string',
      isAtCommand: false,
    ),
    'PERF_TRACKING_COMPRESSION': OBDCommand(
      name: 'PERF_TRACKING_COMPRESSION',
      description: "In-use performance tracking (compression ignition)",
      command: '090B',
      expectedBytes: 4,
      decoderName: 'raw_string',
      isAtCommand: false,
    ),
    'ELM_VERSION': OBDCommand(
      name: 'ELM_VERSION',
      description: "ELM327 version string",
      command: 'ATI',
      expectedBytes: 0,
      decoderName: 'raw_string',
      isAtCommand: true,
    ),
    'ELM_VOLTAGE': OBDCommand(
      name: 'ELM_VOLTAGE',
      description: "Voltage detected by OBD-II adapter",
      command: 'ATRV',
      expectedBytes: 0,
      decoderName: 'elm_voltage',
      isAtCommand: true,
    ),
  };
}
